### ISSUE TITLE
New Public Instance - https://lingva.lunar.icu/

### ISSUE THREAD

**Issue by MaximilianGT500** [TheDavidDelta/lingva-translate#102]
Hello, can you add https://lingva.lunar.icu/ to your Public list?

Thanks,
Maximilian

**Comment by MaximilianGT500** [comment]
Hello, no in use an German VPS Provider with Cloudflare Proxy.

**Comment by TheDavidDelta** [comment]
Please could you tell me the name and URL of your hosting provider?

**Comment by MaximilianGT500** [comment]
Lansol: https://www.lansol.de/
But i will change it, the Provider Limited my Traffic to 1MBit/s

**Comment by TheDavidDelta** [comment]
In case that change is not immediate I'll just add that information for the moment, and then just make another PR when you do the migration.
What do you think?

**Comment by MaximilianGT500** [comment]
Alright, i forgot i use a Proxy at: [proxy.lunar.icu](https://proxy.lunar.icu)
