### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by 1over137** [TheDavidDelta/lingva-translate#103]
What is the sample rate of the audio retrieved from the API?
Also, it would be useful if it shows a button/exposes an endpoint to simply download the audio as a file.

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project!

These are several examples of the URL we currently use for scraping the translation:
+ [test (English)](https://translate.google.com/translate_tts?tl=en&q=test&textlen=4&client=tw-ob)
+ [prueba (Spanish)](https://translate.google.com/translate_tts?tl=es&q=prueba&textlen=6&client=tw-ob)
+ [prova (Catalan)](https://translate.google.com/translate_tts?tl=ca&q=prova&textlen=5&client=tw-ob)

As you can see, it gets 3 params:
+ `tl` is the language code
+ `q` is the translation query
+ `textlen` is the length of the query

Just as a sidenote, the query length has a maximum of 200.
Indeed, you can [take a look at the current implementation](https://github.com/TheDavidDelta/lingva-translate/blob/main/utils/translate.ts#L67) inside the project as it's Free and Open Source.

Unfortunately, I don't know which sample rate it uses, as it's just the default GTranslate voice.

I hope this has been useful.
Regards, David.
