### ISSUE TITLE
Issues in instances

### ISSUE THREAD

**Issue by ManeraKai** [thedaviddelta/lingva-translate#108]
- [translate.alefvanoon.xyz](https://translate.alefvanoon.xyz/) no longer works. @alefvanoon
- [translate.igna.rocks](https://translate.igna.rocks/) is disabled? the parent domain is disabled
- [translate.datatunnel.xyz](https://translate.datatunnel.xyz/) vanished from life. Even the parent domain
- [lingva.esmailelbob.xyz](https://lingva.esmailelbob.xyz/) no longer works. His services page isn't mentioning lingva anymore but mentions SimplyTranslate
- [translate.plausibility.cloud](https://translate.plausibiity.cloud/) the subdomain and parent domain have vanished

Literally the only ones that are working are:
- [lingva.ml](https://lingva.ml/) (Official)
- [lingva.pussthecat.org](https://lingva.pussthecat.org/)
- [lingva.lunar.icu](https://lingva.lunar.icu/)

Updating this list is really important for [LibRedirect](https://github.com/libredirect/libredirect) to function properly

**Comment by itsnotsaved** [comment]
something as yours used in whoogle https://github.com/benbusby/farside (not a web extension)

**Comment by thedaviddelta** [comment]
Hello, I'm very sorry for the big delay.
I just cleaned up the whole instance list in the last PR, which is linked just above this comment.
I hope it solves everything!

Regards, David.
