### ISSUE TITLE
Select text and translate

### ISSUE THREAD

**Issue by Donkey-Doug** [thedaviddelta/lingva-translate#112]
When text is selected on android, a popup menu appears with options such as "copy, cut, paste". Make it possible to have a translate option as well, similar to how firefox provides a search option.

FYI, deepl already does this https://github.com/sakusaku3939/DeepLAndroid

**Comment by thedaviddelta** [comment]
Hello and thanks for your interest in this project!

I'm sorry but this isn't an Android app, but a Webpage. It can be installed as a Progressive Web App, but it still runs inside a browser. It doesn't have the capabilities that native Android apps have.

However, there are a pair of Android native apps based in our API, that can be found in the project's README. You can suggest this idea to them.

Regards, David.
