### ISSUE TITLE
Abnormal memory usage

### ISSUE THREAD

**Issue by karmarcharger** [thedaviddelta/lingva-translate#119]
The docker container seems to be using alot of memory when the app is not being used. Is it suppose to be using this much memory when idle?

Docker Arm64 Image (https://github.com/TheDavidDelta/lingva-translate) 

![image](https://user-images.githubusercontent.com/10364143/174328039-b6d0c186-a36a-4e4b-9143-72e85d77478f.png)

Logs below
`    

> [PWA]   scope: /

Browserslist: caniuse-lite is outdated. Please run:

npx browserslist@latest --update-db

Why you should do it regularly:

https://github.com/browserslist/browserslist#browsers-data-updating

> [PWA] Compile server

Browserslist: caniuse-lite is outdated. Please run:

npx browserslist@latest --update-db

Why you should do it regularly:

https://github.com/browserslist/browserslist#browsers-data-updating

Browserslist: caniuse-lite is outdated. Please run:

  npx browserslist@latest --update-db

  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

info  - Compiled successfully

info  - Collecting page data...

info  - Generating static pages (0/4)

info  - Generating static pages (1/4)

info  - Generating static pages (2/4)

info  - Generating static pages (3/4)

info  - Generating static pages (4/4)

info  - Finalizing page optimization...

Page                               Size     First Load JS

┌   /_app                          0 B             180 kB

├ ● /[[...slug]] (4043 ms)         5.75 kB         186 kB

├   └ / (727 ms)

├ ○ /404 (2951 ms)                 289 B           180 kB

├ ○ /500 (2711 ms)                 282 B           180 kB

├ λ /api/graphql                   0 B             180 kB

├ λ /api/v1/[[...slug]]            0 B             180 kB

└ λ /api/v1/languages/[[...slug]]  0 B             180 kB

+ First Load JS shared by all      180 kB

  ├ chunks/framework.c93ed7.js     42.6 kB

  ├ chunks/main.b7dd7b.js          25.3 kB

  ├ chunks/pages/_app.195061.js    111 kB

  └ chunks/webpack.70ff54.js       866 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)

○  (Static)  automatically rendered as static HTML (uses no initial props)

●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

Done in 135.38s.

yarn run v1.22.15

$ next start --port ${PORT-3000}

ready - started server on 0.0.0.0:3000, url: http://localhost:3000

yarn run v1.22.15

`

**Comment by thedaviddelta** [comment]
Hello and thanks for reporting this!

Unfortunately, can't tell you much about it, because everything seems fine in the logs, and because we (still, #107) don't have official ARM images, so I can't give any official support for some problems that may happen inside them.
For the moment, something that comes to my mind is to make a clean run of the image again, in case there was some problem with data cache inside the container.

I hope this helps somehow.
Regards, David.
