### ISSUE TITLE
Feature request: Three panel input language->target languuage->input language option

### ISSUE THREAD

**Issue by happening-primal** [thedaviddelta/lingva-translate#120]
Great tool, invaluable.

Would you look into providing an option, or other available web page that allows you to see the target language translation translated back into the original language for a little bit of error checking.  There is an app called boomerang that does this, and it seems like it would be fairly easy to someone who knows html (not me :))?

**Comment by thedaviddelta** [comment]
Hello and thanks for the suggestion!

If I understood correctly, what you want could be achieved in Lingva (and most web translators) by using the "swap languages" button, which swaps both the languages and the translation texts.
So, basically, you could simply translate something into Chinese, for example, and then swap the languages and translate it back to English.

For this reason, I don't see any UI changes needed. In addition, we'd like to resemble the UI and UX of other web translators as the own Google Translate.

Regards, David.
