### ISSUE TITLE
Specific URL when installed as an application

### ISSUE THREAD

**Issue by schapira** [thedaviddelta/lingva-translate#123]
Desire: open the translator in specific languages as desktop app
Tries:
- Enter to  https://lingva.ml/iw/de/* in Iridium browser (chromium forks), Windows 10
- Install as an app
- Close browser
- Open the app in the desktop
- Its opens https://lingva.ml (default language setting instead of Hebrew-German )

What's wrong?

**Comment by thedaviddelta** [comment]
Hello!

I think what you are looking for is not a PWA installation, but a desktop shortcut.
The PWA (Progressive Web App) is meant to be installed as an App run by your browser, but like native apps, it should always start in a certain path (this is indeed, the [declared behaviour in our manifest](https://github.com/thedaviddelta/lingva-translate/blob/main/public/manifest.json#L4)).

Anyway, the webapp stores the last used languages in localstorage, so it remembers them for the next opening. If it's not happening to you, take a look whether localstorage is disabled on your browser, or it gets cleared on close. I know Iridium is a privacy-oriented fork so maybe this is the reason.

Regards, David.

**Comment by schapira** [comment]
Hi
thanks for your respond. My browser is set to clear cookies when its close, so thing are not save. I would like to find a way to save the selected languages by url.

**Comment by thedaviddelta** [comment]
Hello again!

That's not something usual at all in webapps, which use other kind of ways of doing that, in the same way you wouldn't expect your GTK or WPF app to have a unique URL for the saved data.
But indeed, Lingva's architecture enables it when purely used in a browser. The thing is that once again you're not looking for PWAs, that resembles a desktop app but running with the browser engine, but for browser bookmarks or desktop shortcuts of the webpage's URLs.

Regards, David.
