### ISSUE TITLE
Text spanning outside frame

### ISSUE THREAD

**Issue by kinmenRP** [thedaviddelta/lingva-translate#133]
In browsers based on mozilla engine (firefox, palemoon, seamonkeys) , midori, when I ask to translate a Chinese text, at the bottom of the source's language form, the transliterated text appears, but it spans outside the frame OR isn't completely shown (firefox). 
![immagine](https://user-images.githubusercontent.com/12298340/187038659-a81b878a-8103-4fc5-9e50-7043a62e2a41.png)

**Comment by thedaviddelta** [comment]
Hello and thanks for your interest in this project.

This is the intended behaviour, not only in Gecko browsers but also in Blink and Webkit ones.
When a translation contains pronunciation text (拼音 in this case) it is shown in a single row next to the helper buttons, and cropped on overflow, so it doesn't cover the whole screen. However, you can see the complete text in a tooltip if you hover over.

I wish this has been helpful for you.
Regards, David.
