### ISSUE TITLE
[Feature Request] Recent buttons next to/above the language selection dropdown

### ISSUE THREAD

**Issue by Asmageddon** [thedaviddelta/lingva-translate#134]
Ideally, a compact interface that displays just that language/country's flag, and a short code, e.g. `✨` for detect, `🇬🇧EN`, `🇵🇱PL`, etc.

**Comment by thedaviddelta** [comment]
Hello and thanks for your interest in this project!

This is a very interesting idea, and a possible interface design to have in the futurely-planned UI refactor.
Or well, at least the lang codes, without the flags, or with any other kind of identificatin that may have to be discused. I don't like them as some languages (and not only a few) have no related national flag, as emoji flags are unfortunately only given to nation-states and not to language communities.
But for the moment and until the Lingva refactor, the interface will stay similar to current.

Thank you again.
Regards, David.
