### ISSUE TITLE
Add instance translate.jae.fi

### ISSUE THREAD

**Issue by jae1911** [thedaviddelta/lingva-translate#135]
Hey there, I recently switched my translate instance to Lingva.  
Here are the info:

Domain: translate.jae.fi
Hosting: Jae Lo Presti
SSL Provider: Let's Encrypt

**Comment by thedaviddelta** [comment]
Hello and thank you so much for hosting Lingva!
About the hosting provider, do you self-host it in local machines owned by yourself, or do you use any online hosting services? If it's the first one, I may include "self-hosted" as the hosting. Tell me whether this is good for you.
Regards, David.

**Comment by jae1911** [comment]
Hey there, everything is self-hosted, the physical servers and IPs are also announced by myself with my very own network (https://bgp.he.net/as211696).  
It's much more than just buying a VM at Hetzner and hosting it myself :)

**Comment by thedaviddelta** [comment]
Yeah I guessed it. Perfect. I'll write "self-hosted" then!

**Comment by thedaviddelta** [comment]
Just merged it!! :smile: Thanks again!
