### ISSUE TITLE
Add support for Kurdish (Sorani)

### ISSUE THREAD

**Issue by alandio** [thedaviddelta/lingva-translate#137]
Some languages where added recently one of which were kurdish (sorani)
Can you please update the language list based on google's ones.

**Comment by thedaviddelta** [comment]
Hello and thanks for your interest in the project!

Thanks for the notice. I didn't know they added more languages to the Google Translator.
I've just added them in [this commit to the scraper](https://github.com/thedaviddelta/lingva-scraper/commit/362397925e4a654150c8bc0092ce3ebec678659b), and then updated the scraper version in #138.
Should be merged in a couple of minutes!

Regards, David.
