### ISSUE TITLE
Unable to connect https://lingva.ml/

### ISSUE THREAD

**Issue by Cyber-Syntax** [thedaviddelta/lingva-translate#146]
Is there a problem on the server or me?

**Comment by thedaviddelta** [comment]
It works for me in several devices and browsers, so I don't think there's any issue.

Regards, David.

**Comment by gbdomubpkm** [comment]
Yes. Currently doesn't work. I can't connect now.

**Comment by Cyber-Syntax** [comment]
I solved this problem by changing DNS.

**Comment by TCAtrevor** [comment]
I'm not able to get an IP for lingva.ml from several DNS servers. They respond with "Non-existent domain". I was only able get a response from one of the DNS root servers.

**Comment by TCAtrevor** [comment]
https://github.com/TheDavidDelta/lingva-translate/issues/73#issuecomment-1007413553
This comment helped though, at least for now.
