### ISSUE TITLE
[Bug] Question marks don't work

### ISSUE THREAD

**Issue by wuniversales** [TheDavidDelta/lingva-translate#16]
![image](https://user-images.githubusercontent.com/48658161/116758542-8dcaaa00-aa10-11eb-82cb-8124c111d0b1.png)

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project.

But indeed this is not a bug, it's exactly the same translation as in GTranslate. The fact that this translation doesn't have question marks included seems a particular case and is up to Google as Lingva is just a frontend.
![imagen](https://user-images.githubusercontent.com/6679900/116759118-e3538680-aa11-11eb-9fa2-a122ddda2a8a.png)

Regards, David.
