### ISSUE TITLE
Add https://translate.trom.tf to the instances list

### ISSUE THREAD

**Issue by tio-trom** [TheDavidDelta/lingva-translate#163]
We've setup an instance at https://translate.trom.tf - if you want you can add it to your instances list. Thanks!

**Comment by vitonsky** [comment]
@tio-trom hi, thanks for up a public instance. What plans you have on this instance?
Is this instance ready for the intensive use? If yes, i could add your endpoint as default for a https://github.com/translate-tools/core, the library with a translation primitives that used by projects with a big number users, like a [Linguist translator](https://github.com/translate-tools/linguist), if you can promise that instance are stable and will exists a long time.

**Comment by tio-trom** [comment]
Thank you for replying. After more than a month of testing I think that Google is limiting our server. I can definitely keep it up and running, we already have plenty services at trom.tf, but I am concerned that if Google limits us or even bans our IP, it is difficult to manage that. Perhaps for now is not reliable in that regards so I would better close this issue.
