### ISSUE TITLE
Weblate Integration

### ISSUE THREAD

**Issue by aluyama** [TheDavidDelta/lingva-translate#170]
Weblate is a libre software web-based continuous localization system. It has many features, supports 17 machine translation engines, supports many file formats, built-in quality checks, easy to deploy with minimum resources (or possible to run on your own laptop; e.g. using docker).
https://github.com/WeblateOrg/weblate
https://docs.weblate.org/en/latest/admin/addons.html
https://docs.weblate.org/en/latest/formats.html
(Text files, CSV files, Excel / Document files, Subtitle files, GNU gettext, HTML files, JSON files, XML / XLIFF files and more)
https://weblate.org/en/download/

If you need to translate documents, sheets, contents in large / complex files; then machine translation always helps to save the time. Also, if you use google services (e.g. google docs, google sheets); you can translate documents to different languages easily https://www.bu.edu/dli/resources/technology-tools/google-translation-features-translate-your-documents/

I also have used the google translation API (free quota) but when register to use the API, they take the government ID/passport documents and other KYC details.

Lingva comes with API support. If someone can create this, everyone will benefit. you can be find code for existing engines as well. By the way, @thedaviddelta seems busy
https://docs.weblate.org/en/latest/admin/machine.html
https://docs.weblate.org/en/latest/admin/machine.html#custom-machine-translation
_**You can also implement your own machine translation services using a few lines of Python code.**_

If you want to know something else, you can read the docs https://docs.weblate.org/en/latest/ and inspect the weblate code.

**Comment by vitonsky** [comment]
@aluyama you can check the https://github.com/translate-tools/core, a project with translation primitives.
It includes few free translators implementations and powerful utils for batch translating

**Comment by aluyama** [comment]
>It includes few free translators implementations and powerful utils for batch translating

@vitonsky I don't have enough coding knowledge :( May be, i still need to find a way to connect lingva into weblate to achieve my goal. I also expect to use my own TM (translation memory). _(**a weblate feature)_
