### ISSUE TITLE
WebExtension

### ISSUE THREAD

**Issue by KyleFN** [TheDavidDelta/lingva-translate#22]
It would be great to have this available as a WebExtension, for translating small pieces of text as well as webpages.

**Comment by itsnotsaved** [comment]
https://github.com/sienori/simple-translate
https://github.com/sienori/simple-translate/issues/293
(i'm not sure if they implement that)

**Comment by TheDavidDelta** [comment]
Hello and thanks you both for your interest in the project.

It'd be really cool but creating a browser extension for that is not one of my current goals. There are many Open Source addons that already use GTranslate (like the one @itsnotsaved mentioned) and it'd be better to contribute to any of them adding the said support.

Regards, David.

**Comment by itsnotsaved** [comment]
@KyleFN Follow https://github.com/sienori/simple-translate/issues/293 It has added to a milestone
