### ISSUE TITLE
404 occur when source contain characters or multiple languages

### ISSUE THREAD

**Issue by Aikatsui** [TheDavidDelta/lingva-translate#23]
Eg: `Check our <strong>Privacy Policy</strong>.`
You can check random contents for multiple languages

**Comment by Aikatsui** [comment]
https://github.com/TheDavidDelta/lingva-translate/issues/18

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in this project.

Sorry for my late response, but I'm glad you found the other issue I was going to mention.
Unfortunately, it seems no one have still replied at the issue in Next's repo. I hope someone pays attention to it soon.

Regards, David.

**Comment by TheDavidDelta** [comment]
Hello again.

Just wanted you to know there was an important update about this problem on the other issue. Go take a look!

Regards, David.
