### ISSUE TITLE
TTS icon is hidden by Grammarly extension

### ISSUE THREAD

**Issue by Daksh777** [TheDavidDelta/lingva-translate#28]
I'm sorry if I shouldn't be reporting an extension issue here but I have Grammarly installed and the Grammarly icons overlaps the TTS icon (in the translate from box)
![image](https://user-images.githubusercontent.com/43648146/122000539-9dd5f780-cdcc-11eb-927a-62ee3ea2522f.png)

This might help: https://stackoverflow.com/questions/37444906/how-to-stop-extensions-add-ons-like-grammarly-on-contenteditable-editors

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

I've changed property the StackOverflow guy says and deployed to a preview branch.
[This](https://lingva-translate-git-grammarly-fix-1-thedaviddelta.vercel.app/) is the preview link. Tell me if it works and I'll merge to main the next evening.

Regards, David.

**Comment by Daksh777** [comment]
That works well, you may push it to the main repo.

**Comment by TheDavidDelta** [comment]
Perfect, will merge tonight.
