### ISSUE TITLE
API Request for supported languages

### ISSUE THREAD

**Issue by ifrendas** [TheDavidDelta/lingva-translate#40]
Could an API request be added to get a list of supported languages and their codes (Like [Libre Translate's](https://libretranslate.com/docs/#/translate/get_languages) request)? You can get these by downloading [the internal JSON](https://raw.githubusercontent.com/TheDavidDelta/lingva-translate/main/utils/languages.json), but it would be nice to get it directly from the server (in case the repo is ever moved or something like that).

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

I've just added this endpoint, and its GraphQL equivalent as well.
In addition, I've added the option to specify the languages list you want to retrieve (only source or only target languages) as well. Obviously, you can still retrieve the full list by leaving the parameter empty.

Tell me what do you think [about the implementation](https://github.com/TheDavidDelta/lingva-translate/tree/api-languages-1). I'll merge later.

Regards, David.
