### ISSUE TITLE
Change port docker

### ISSUE THREAD

**Issue by trentwiles** [TheDavidDelta/lingva-translate#54]
I ran the following command as port 3000 on my server is busy:

```
docker run -p 3030:3030 -e site_domain=example.com thedaviddelta/lingva-translate:latest
```

Once this finished running, NextJS tried to run the server on 3000 instead. Is there any way this can be fixed?

**Comment by TheFrenchGhosty** [comment]
@RiversideRocks It's docker, so just change the 3000 port, ie:

`docker run -p [YOURPORT]:3030 -e site_domain=example.com thedaviddelta/lingva-translate:latest`

**Comment by TheDavidDelta** [comment]
Very thanks @TheFrenchGhosty for already replying!

As he said, that's just intentional. The server always runs on 3000 inside its own Docker environment, and the `-p` param is used for telling Docker to which port of the real machine should be bound.

Regards, David.
