### ISSUE TITLE
Lingva docker image isn't working on raspberry pi

### ISSUE THREAD

**Issue by cinetube** [TheDavidDelta/lingva-translate#62]
Lingva docker image isn't working on raspberry pi. Please check the issue.

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project.

Sorry, could you give me more details?
In theory, you could host Lingva in a platform-agnostic way in any device by using Docker. But if you're using the standard way with NodeJS, you shouldn't had any problem. I had a private instance in a local Raspberry (with Ubuntu Server 20.04) working without issues.
Please provide me more details about your problem.

Regards, David.

**Comment by cinetube** [comment]
<img width="713" alt="Screenshot 2021-11-01 175031" src="https://user-images.githubusercontent.com/23441775/139667243-2072d500-09e2-4a37-961a-91e1b2b36d0b.png">

Please check the attached image. 

I am also using Ubuntu Server 20.04 on my Raspberry pi 4B

**Comment by TheDavidDelta** [comment]
Okey, try adding `--platform linux/arm64/v8` to the Docker run command (after the last environment).

If it doesn't work, simply build the image from the provided `Dockerfile` with the following command:
```
docker build -t lingva-translate .
```

It will create an image the same way it's created on the CI but based on your Raspbery's arch. Remember to replace `thedaviddelta/lingva-translate:latest` with `lingva-translate` on the Docker run.

I'll take a look at creating several official images with several archs more calmly in the future.

Regards, David.

**Comment by cinetube** [comment]
Thank you very much for your quick response. 

I build the docker image but while I am trying to run it getting th
<img width="550" alt="Screenshot 2021-11-01 193101" src="https://user-images.githubusercontent.com/23441775/139679606-8a42a50c-271b-4248-8134-f9cf7e878266.png">
e following error.

**Comment by TheFrenchGhosty** [comment]
@cinetube Ah, that's a problem, it seems to be using functions not available on arm64

**Comment by TheDavidDelta** [comment]
No, this is not an ARM problem. It's a Node 17 bug. Indeed, I just got that same bug on my machine.

Node 17 released 1 week ago and it seems it's still buggy. For some reason, the default Alpine image is using Node Current (17) instead of LTS, so I changed the version to LTS.

Try to pull the git repo and build again and it should work perfectly.

Sorry for the inconvinience.
