### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by farishsyazwan** [TheDavidDelta/lingva-translate#73]
![pls](https://user-images.githubusercontent.com/95562040/148148168-c5b00e2f-c112-4e05-b914-e34f9db26a0b.PNG)

Other website work. Is lingva.ml down right now?

**Comment by NS2555** [comment]
seems like the site works now

**Comment by farishsyazwan** [comment]
> seems like the site works now

yeah

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in the project.

Based on your screenshot, this seems like a DNS problem. This means that the website was probably online, but not reachable through the common used name (lingva.ml). The thing is that DNS issues, unless standard HTTP connection ones, can occur regionally.

In summary, when your computer resolves the name, it happens recursively through several DNS resolvers. Firstly, your own computer cache, then your router's cache, then your ISP provider, then some other regional server, etc. So one of them may have wrong information, or simply fail the query, and the whole web request fails.

I didn't have any problem with Lingva these days, and the repository hasn't been set on fire either with a lot of issues related to this, so I suppose this was a regional DNS problem. Anyway, I'm glad it's working correctly again, and in case there's any DNS problem again you can try with any of the domains associated to the main Lingva instance

+ [lingva-translate.vercel.app](lingva-translate.vercel.app)  
+ [lingva-translate-thedaviddelta.vercel.app](lingva-translate-thedaviddelta.vercel.app)  
+ [lingva-translate-git-main-thedaviddelta.vercel.app](lingva-translate-git-main-thedaviddelta.vercel.app)  
+ [lingva.ml](lingva.ml)  

or, in case it's a full server failure, you can also try with any of the [other Lingva instances](https://github.com/TheDavidDelta/lingva-translate#instances).

Regards, David.
