### ISSUE TITLE
browser extension

### ISSUE THREAD

**Issue by happuji** [TheDavidDelta/lingva-translate#75]
hello i have a very good idea. for that . 

my English bad . so I use[ google translate extension ](https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb)
but I don't like ,but I don't have other options to use. i have literally tried every translator extension but this was working good . but u know the google as privacy . so it would be good if lingava could be transformed to a web extension  with some good theme and fast ,efficiency 

tbh I am not a dev, even don't kwno programing 
but I want something like this but in privacy towards. 

hope u got the thing so pls think about making it to a extension

**Comment by CavaleriOmar** [comment]
Same situation...

Bad in English and I find myself moving on to Google Translate ... but I don't like the Big G (even if some things pulled out of them work just fine) and I wouldn't mind breaking away from them on translation tracking as well.

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in this project.

This was already requested by some people time ago, in #22.
As I said at the moment, there are many Free and Open Source addons that already use GTranslate and other engines and, as Lingva is FOSS and has an open API, it would be better to contribute to any of them and add the said support.
I don't know if someone has already done this but unfortunately I have no news about it.

Regards, David.

**Comment by itsnotsaved** [comment]
@happuji @CavaleriOmar Follow https://github.com/sienori/simple-translate/issues/293 It has added to a milestone

**Comment by itsnotsaved** [comment]
Follow https://github.com/sienori/simple-translate/issues/293 It has added to a milestone
