### ISSUE TITLE
Feature Request: Translating Websites

### ISSUE THREAD

**Issue by 0lhi** [TheDavidDelta/lingva-translate#76]
Google Translate supports translating Websites. Would be awesome if Lingva could offer that as well!

**Comment by TheDavidDelta** [comment]
Hello and thanks for your interest in the project.

This is a very interesting feature from GTranslate, which works in a very similar way as a translation addon does but even a little trickier, by embedding the whole original page on a custom domain.
For this purpose, I would recommend using a translation addon on the browser. I don't know if anyone has already implemented the Lingva API in any of them at the moment, but if it exists it would be perfect.

Regards, David.

**Comment by itsnotsaved** [comment]
Follow https://github.com/sienori/simple-translate/issues/293 It has added to a milestone
