### ISSUE TITLE
[Question] It Uses Google Translate but No Google Services?

### ISSUE THREAD

**Issue by arandorion** [TheDavidDelta/lingva-translate#77]
> Alternative front-end for Google Translate . . . Lingva scrapes through GTranslate and retrieves the translation without using any Google-related service, preventing them from tracking.

Sorry if these are dumb questions, but I'm confused. The description says it's a front-end for Google Translate. Then it says it "scrapes through GTranslate".  GTranslate (GTranslate.io) is "a leading website translation services provider". Is it scraping through some data provided by GTranslate? Or is GTranslate in this context shorthand for Google Translate?

Then it says it "retrieves the translation without using any Google-related service". If it's a front-end for Google Translate, then it's using at least one Google-related service—Google Translate. What am I misunderstanding here?

Sorry if I'm being dense. This project looks interesting, but I want to understand how it relates to Google before I begin using it.

Thanks

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in the project.

Don't worry about your questions. I didn't even know about the existence of GTranslate. As you have already deduced, GTranslate is a shorthand for Google Translate in the whole Readme.
And about the Google scraping, someone already asked me this same question and I did a more extensive reply in #67, but in summary, Lingva request and scrapes the original GTranslate webpage without using any official API nor revealing the user's address.

Regards, David.
