### ISSUE TITLE
New instance!

### ISSUE THREAD

**Issue by Jenni32222** [TheDavidDelta/lingva-translate#79]
Hi! I am hosting an instance of Lingva at translate.datatunnel.xyz!
Hosting at Hetzner using Let's Encrypt :)

Would you be so kind to add it to the list?

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in the project.

Amazing! Thanks for hosting Lingva! :smiley: 
I'll make a self-PR as soon as possible, but please let me first solve #80 so all the CIs can run correctly.
Sorry for the inconvenience.

Regards, David.

**Comment by TheDavidDelta** [comment]
Done! Already on the main Readme!
