### ISSUE TITLE
lingva.ml is down

### ISSUE THREAD

**Issue by ajs256** [TheDavidDelta/lingva-translate#80]
![image](https://user-images.githubusercontent.com/67526318/150663775-9cf8f6d4-fad8-4fa8-9b57-2a3c375c8bf3.png)

**Comment by itsnotsaved** [comment]
https://github.com/TheDavidDelta/lingva-translate#instances

**Comment by TheDavidDelta** [comment]
Thanks for the notice.

I'm currently investigating the problem and looking for solutions as fast as possible.
In the meantime, as @itsnotsaved suggested, you can use any other instance in the list.
Sorry for the inconvenience.

Regards, David.

**Comment by TheDavidDelta** [comment]
I'm very happy to announce that Vercel has just sponsored Lingva, so the website is already up again! You can read the announcement in my [Twitter](https://twitter.com/thedaviddelta/status/1485389688533921792) and [Mastodon](https://mastodon.social/@TheDavidDelta/107674303332949977) accounts.
