### ISSUE TITLE
Add instant translate feature

### ISSUE THREAD

**Issue by IronMaltese** [TheDavidDelta/lingva-translate#89]
I continue to switch back to normal google translate because of the need to press translate everytime I enter a word, I would appreciate if this feature could be implemented

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in this project.

Indeed, we already have a feature for that. It's the lightning button under (or next to on mobile) the translate one. You can activate it and the preference gets saved to the browser for next times too.

Regards, David.
