### ISSUE TITLE
Voice To Text?

### ISSUE THREAD

**Issue by trymeouteh** [TheDavidDelta/lingva-translate#93]
A voice to text feature which can modify the voice with some random filters to anonymise the users voice (such as pitch) before sending it over to Google Translate to convert into text

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in the project.

I'm sorry but I'm not sure that I'm understanding you correctly. Is your request GTranslate's text-to-speech private API (that I'm not sure it exists) but, in addition, to model the recorded voice for Google to not be able to recognize it?

I'm sorry but I think this is a bit crazy. Instead, we could implement some text-to-speech system on our own, but it's a very big topic and I don't know if it's needed when you can use any Free (as in Freedom) text-to-speech software on your system that, in addition, can be used on the rest of webpages and applications.

Regards, David.
