### ISSUE TITLE
Save the selected language as a cookie

### ISSUE THREAD

**Issue by ELWAER-M** [TheDavidDelta/lingva-translate#96]
Hi, thanks for that great project!

i have a suggestion, it would be nice if the selected languages saved as a cookie in the browser, instead of setting them every time after refreshing the page, maybe an button or a switch for saving them is a good idea

**Comment by TheDavidDelta** [comment]
Hi and thanks for your interest in the project.

I'm glad to tell you that this is indeed already implemented! It's not with cookies but with localStorage, the preferred way, but the functionality is working since some months ago! Is it not working for you?

Regards, David.

**Comment by ELWAER-M** [comment]
oh, thanks. it seems to be a problem with my browser or something
