### ISSUE TITLE
[design error] play audio button

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [TheDavidDelta/lingva-translate#99]
So I have noticed a weird behavior? Not a bug per se but it's weird for sure

So when you type stuff in the big box to translate and want to play audio you need to press outside of translation text box first to be able to press on audio button which is kinda unexpected behavior 

Here is a video to explain what I mean:
https://user-images.githubusercontent.com/28893833/157061970-8f63aca4-01a2-41fa-b3a6-aa6fec72d012.mp4

So it's a little CSS or design bug easy to solve I assume?
___
PS: yes I play TF2 
PS 2: video for some reason works only in chromium browsers so make sure you use that!

**Comment by TheDavidDelta** [comment]
Hi and thanks for the bug report!

It seems that the textarea was stacking over the buttons on focus for some reason.
I just pushed a PR with the fix, will merge ASAP.

Regards, David.
